### ISSUE TITLE
failed to complie when using beacon sdk

### ISSUE THREAD

**Issue by krobert** [helpscout/beacon-android-sdk-sample#180]
Hey, 

Im doing a version bump in our application, but i cannot do it because the compiler fails to run because of beacon.
Here is the log:

```
Execution failed for task ':platform-mobile:mergeExtDexProductDebug'.
> Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
   > Failed to transform beacon-4.0.0.aar (com.helpscout:beacon:4.0.0) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=productDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform android-common-1.8.9.aar (com.helpscout.internal:android-common:1.8.9) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=productDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform kotlin-common-1.8.9.jar (com.helpscout.internal:kotlin-common:1.8.9) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.localToProject=public, org.jetbrains.kotlin.platform.type=jvm}.
      > Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=productDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform moshi-kotlin-1.13.0.jar (com.squareup.moshi:moshi-kotlin:1.13.0) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=productDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform moshi-adapters-1.13.0.jar (com.squareup.moshi:moshi-adapters:1.13.0) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=productDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform converter-moshi-2.9.0.jar (com.squareup.retrofit2:converter-moshi:2.9.0) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':platform-mobile:productDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=productDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-dex, asm-transformed-variant=productDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for AsmClassesTransform: /root/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Record requires ASM8

```
**Technical details**

- Beacon version: 4.0.0

**Steps to reproduce**

Upgrade everything in your sample app (not the sdk):
    1. upgrade to geradle wrapper 7.3.3
    2. use target/compile sdk 32
    3. use build tools 32.0.0
    4. upgrade moshi to 1.13.0

Can i expect any dependency upgrade fix? 
   
  Thanks,
  Robert

**Comment by krobert** [comment]
@jotaemepereira I have to upgrade, because `1.12.0` doesnt support new coroutines and kotlin version.
If i dont upgrade, i have to stop upgrading those as well, and i will be stuck on old language, which is not ideal.

The bug you are referring of is something im aware, it was present in `7.0.3` they promised a fix in `7.2`, its in the comments, but  im using `7.3.3`. 
It should work fine, but its still there, because your sdk doesnt use the latest moshi.

**Comment by jotaemepereira** [comment]
@krobert I've just pushed a branch named [updated-moshi](https://github.com/helpscout/beacon-android-sdk-sample/tree/updated-moshi) that does the following:
- Updates Gradle to `7.3.3`
- Updates the `targetSdkVersion` and `compileSdkVersion` to 32
- Adds Moshi as a dependency with the `1.13.0` version

The sample apps are working and no problems arise when running them.

> The bug you are referring of is something im aware, it was present in 7.0.3 they promised a fix in 7.2, its in the comments, but im using 7.3.3.

I think you are getting confused between the Gradle version and the Android Gradle plugin version, if you see the [release notes](https://developer.android.com/studio/releases/gradle-plugin#7-0-0) on the AGP you will see that the latest stable version is `7.0.4` while the `7.2` is only shipped with the Canary version of Android Studio, something that we do not support yet because we support the latest stable one.

I recommend downgrading your version of the AGP to `7.0.4` and try upgrading Moshi to the latest version.

**Comment by krobert** [comment]
@jotaemepereira you are right i mixed up the 2 versions, AGP is 7.0.4 , but still not working for me.
Im running on ci which runs a clean build, maybe its cached for you?

**Comment by jotaemepereira** [comment]
@krobert Question, do you have Jetifier enabled in your project? Disabling could help you on fixing this issue. I've seen that helped with this issue in other libraries.

**Comment by krobert** [comment]
@jotaemepereira sadly it must be enabled because of other libraries, 
I tried adding it to gradle properties to skip it:
`android.jetifier.ignorelist=moshi,beacon`
I played with the namings also, but its not doing anything. 
I think i will  just drop moshi and move to kotlin serialization. 

So we can close this issue, because its not an sdk problem, thanks for your help.

**Comment by jotaemepereira** [comment]
@krobert Sorry to hear that you weren't able to get it working and you have to move to another serialization library 😓 . I will let you know if I find something else.
