### ISSUE TITLE
The "Ask" tab is asking which channel I prefer even when chat is disabled and there is only one option.

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-android-sdk-sample#95]
Beacon version: 2.1.0.

Steps to reproduce:
1: Set a beacon to neutral mode
2: Set chat to disabled
3: Open the beacon from the mobile app and press "Ask"

Expected result:
I would expect to be taken to the contact form

Actual result:
I am being asked which channel I prefer even though there is only one option (email).

This is not consistent with the web beacon that shows the preferred channel question only if there is more than one option.

**Comment by shaunmcilroy** [comment]
Hey Simon. Thanks for the feedback. I've logged your request with the team regarding presenting a consistent behaviour and we'll keep you in the loop as that conversation progresses. 

Internal tracking card: https://helpscout.atlassian.net/browse/ANDSDK-426

**Comment by sipersso** [comment]
Any updates on this? There is some additional strangeness to the current behavior. 

Consider this scenario:
1: Open the beacon with chat disabled and docs enabled:
2: Press ask: You are presented with the "start a conversation" view and being asked which channel you prefer even though there is only one (email).
3: Press email
4: Press back.

Expected: 
I expected back to take me back to the previous screen. In this case this would be the "start a conversation" in step 2.

Actual:
A spinner is shown for a split second, the beacon forgets that I was on the ASK tab and goes back to "Answers". 

We have had our disagreements with the navigation of the beacon in general about how the navigation buttons are used. But if X is used to close the beacon and back is back in the navigation stack, I would expect that back would actually take me back one step, not two.

**Comment by shaunmcilroy** [comment]
Hey there. No updates on this one yet as per your original request, Simon. This requires some additional consideration on our side from our design team so while the conversation is in progress I don't have an ETA yet. We'll keep you updated as that progresses.

**Comment by sipersso** [comment]
Thanks for the feedback. 

Another interesting observation:

If you follow the steps in my previous comment, but use the hardware back button instead of using the back button in the navigation toolbar in step 4, you get a different result. 

If you press back from the toolbar, the "ask" tab is not being remembered correctly and you are taken two steps back. But if you press the hardware back button from the contact form you are taken to the answers tab, which is what I expected. This must be a bug right? It shouldn't matter if I press the hardware back or use the back button in the toolbar.

**Comment by scottyab** [comment]
hi again @sipersso , I'm pleased to mention we have fixed this issue as part of our 2.2.0 release. Please see the [changelog](https://github.com/helpscout/beacon-android-sdk-sample/blob/master/CHANGELOG.md) for full details. 

As stated in the other issue, please note there is a breaking change in 2.2.0, you will need to remove the reference to `beacon-core` from your Gradle dependencies (in your build.gradle file). To simplify things going forward we've merged `beacon-core` into the `beacon-ui` module. 

If you encounter any problems, please create a Github issue. 

Thanks,
Scott and mobile team @ Help Scout.

**Comment by sipersso** [comment]
Hi @scottyab! I just changed to use the new 2.2.0 update and I am afraid the issue is not fixed. 

I did the following
1: Set a beacon to neutral mode
2: Set chat to disabled
3: Open the beacon from the mobile app and press "Ask"

And there doesn't seem to be a difference compared to 2.1.0. There is still the "which channel do I prefer" - question, even though chat is disabled.
